# Learn Python

### Python Packages - NumPy

##### Source: https://numpy.org/
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is licensed under the BSD license, enabling reuse with few restrictions.

### Importing NumPy Package

In [1]:
import numpy as np

##### Note: Vectors are 1-D and Matrices are 2-D Arrays in NumPy

### Arrays

In [8]:
# Following is an example of a list
simpleList = [1,2,3,4,5]
simpleList

[1, 2, 3, 4, 5]

In [9]:
simpleNPArray = np.array(simpleList)
simpleNPArray

array([1, 2, 3, 4, 5])

In [10]:
simpleListOfLists = [[1,2,3], [4,5,6], [7,8,9]]
simpleListOfLists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
simpleNPMatrix = np.array(simpleListOfLists)
simpleNPMatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Ranges in NumPy

In [15]:
# arange function helps to create a range of values between two limits.
# Note: The first parameter is the start and second the end. The start value is inclusive and end value is exclusive.
# You can define the interval/step for the values too.
simpleRange = np.arange(0,100,10)
simpleRange

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
# If only 1 value is given then NumPy considers it as the number of values required.
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Zeros and Ones

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### Equally spaced values in a range

In [28]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [29]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

### Identity Matrix

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Random Numbers for Arrays and Matrices

##### Creates a list of random values that are uniformly distributed between 0 and 1

In [34]:
np.random.rand(3,2)

array([[0.46166242, 0.32093944],
       [0.9600662 , 0.89560923],
       [0.97129938, 0.92640267]])

In [36]:
np.random.rand(5)

array([0.81826545, 0.16755346, 0.8311501 , 0.51940158, 0.03648709])

In [37]:
# Randn creates a list of values that are normally distributed.
np.random.randn(2,3)

array([[ 2.18685089, -0.45878291, -1.79372613],
       [-0.02683136,  1.2170876 , -1.24959799]])

In [39]:
#Random Integers in a range
np.random.randint(5,100,3)

array([39, 43, 84])

### Reshaping Arrays

In [40]:
simpleRange

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
simpleRange.reshape(5,2)

array([[ 0, 10],
       [20, 30],
       [40, 50],
       [60, 70],
       [80, 90]])

### Finding the shape of an array

In [42]:
simpleRange.shape

(10,)

In [43]:
simpleRange.reshape(5,2).shape

(5, 2)

### Finding the datatype of an array

In [44]:
simpleRange.dtype

dtype('int32')

### Transposing a Matrix

In [46]:
simpleRange.reshape(5,2).T

array([[ 0, 20, 40, 60, 80],
       [10, 30, 50, 70, 90]])

### Selection in Arrays and Matrices

In [53]:
simple = np.arange(10)
simple

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
simple[3]

3

In [55]:
simple[2:5]

array([2, 3, 4])

In [56]:
simple[[2,3]]

array([2, 3])

In [47]:
values = simpleRange.reshape(5,2)

In [48]:
values[1]

array([20, 30])

In [50]:
values[2,1]

50

### Broadcasting

In [57]:
sampleArray = np.arange(10,250,40)
sampleArray

array([ 10,  50,  90, 130, 170, 210])

In [58]:
subsetOfSampleArray = sampleArray[2:5]
subsetOfSampleArray

array([ 90, 130, 170])

In [59]:
subsetOfSampleArray[:] = 1001
subsetOfSampleArray

array([1001, 1001, 1001])

In [60]:
sampleArray

array([  10,   50, 1001, 1001, 1001,  210])

In [62]:
# Broadcasting changes the source values.
# Subsetting only creates a view of the source and not a copy.

In [ ]:
# If you don't want to broadcast the values and instead only change it in the newer ones, user COPY.

In [63]:
copyOfSampleArray = sampleArray.copy()
copyOfSampleArray

array([  10,   50, 1001, 1001, 1001,  210])

In [64]:
copyOfSampleArray[:] = 101
copyOfSampleArray

array([101, 101, 101, 101, 101, 101])

In [65]:
sampleArray

array([  10,   50, 1001, 1001, 1001,  210])

### Matrix Indexing

In [66]:
sampleMatrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
sampleMatrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [67]:
sampleMatrix[1][2]

7

In [68]:
sampleMatrix[1,2]

7

In [79]:
sampleMatrix[0:2][1:3]

array([[5, 6, 7, 8]])

In [73]:
sampleMatrix[:,1:2]

array([[ 2],
       [ 6],
       [10],
       [14]])

In [80]:
sampleMatrix[:,(1,3)]

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [81]:
# Changing the order of output
sampleMatrix[:,(3,1)]

array([[ 4,  2],
       [ 8,  6],
       [12, 10],
       [16, 14]])

### Selection Techniques

In [85]:
sampleArray = np.arange(1,100, 5)
sampleArray

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [86]:
sampleArray[sampleArray > 50]

array([51, 56, 61, 66, 71, 76, 81, 86, 91, 96])

### Array Operations

In [87]:
sampleArray + sampleArray

array([  2,  12,  22,  32,  42,  52,  62,  72,  82,  92, 102, 112, 122,
       132, 142, 152, 162, 172, 182, 192])

In [88]:
sampleArray - sampleArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [89]:
sampleArray / sampleArray

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [90]:
sampleArray/10

array([0.1, 0.6, 1.1, 1.6, 2.1, 2.6, 3.1, 3.6, 4.1, 4.6, 5.1, 5.6, 6.1,
       6.6, 7.1, 7.6, 8.1, 8.6, 9.1, 9.6])

In [91]:
10 / sampleArray

array([10.        ,  1.66666667,  0.90909091,  0.625     ,  0.47619048,
        0.38461538,  0.32258065,  0.27777778,  0.24390244,  0.2173913 ,
        0.19607843,  0.17857143,  0.16393443,  0.15151515,  0.14084507,
        0.13157895,  0.12345679,  0.11627907,  0.10989011,  0.10416667])

In [92]:
sampleArray + 10

array([ 11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,  66,  71,
        76,  81,  86,  91,  96, 101, 106])

In [93]:
np.sqrt(sampleArray)

array([1.        , 2.44948974, 3.31662479, 4.        , 4.58257569,
       5.09901951, 5.56776436, 6.        , 6.40312424, 6.78232998,
       7.14142843, 7.48331477, 7.81024968, 8.1240384 , 8.42614977,
       8.71779789, 9.        , 9.2736185 , 9.53939201, 9.79795897])

In [94]:
np.exp(sampleArray)

array([2.71828183e+00, 4.03428793e+02, 5.98741417e+04, 8.88611052e+06,
       1.31881573e+09, 1.95729609e+11, 2.90488497e+13, 4.31123155e+15,
       6.39843494e+17, 9.49611942e+19, 1.40934908e+22, 2.09165950e+24,
       3.10429794e+26, 4.60718663e+28, 6.83767123e+30, 1.01480039e+33,
       1.50609731e+35, 2.23524660e+37, 3.31740010e+39, 4.92345829e+41])

In [95]:
np.log(sampleArray)

array([0.        , 1.79175947, 2.39789527, 2.77258872, 3.04452244,
       3.25809654, 3.4339872 , 3.58351894, 3.71357207, 3.8286414 ,
       3.93182563, 4.02535169, 4.11087386, 4.18965474, 4.26267988,
       4.33073334, 4.39444915, 4.4543473 , 4.51085951, 4.56434819])

In [96]:
np.max(sampleArray)

96

In [97]:
np.min(sampleArray)

1

In [98]:
# To get the index position of the highest / smallest value
np.argmax(sampleArray)

19

In [99]:
np.argmin(sampleArray)

0

In [100]:
np.sin(sampleArray)

array([ 0.84147098, -0.2794155 , -0.99999021, -0.28790332,  0.83665564,
        0.76255845, -0.40403765, -0.99177885, -0.15862267,  0.90178835,
        0.67022918, -0.521551  , -0.96611777, -0.02655115,  0.95105465,
        0.56610764, -0.62988799, -0.92345845,  0.10598751,  0.98358775])

In [101]:
np.cos(sampleArray)

array([ 0.54030231,  0.96017029,  0.0044257 , -0.95765948, -0.54772926,
        0.64691932,  0.91474236, -0.12796369, -0.98733928, -0.43217794,
        0.7421542 ,  0.85322011, -0.25810164, -0.99964746, -0.30902273,
        0.82433133,  0.77668598, -0.38369844, -0.99436746, -0.18043045])

In [102]:
np.tan(sampleArray)

array([ 1.55740772e+00, -2.91006191e-01, -2.25950846e+02,  3.00632242e-01,
       -1.52749853e+00,  1.17875355e+00, -4.41695568e-01,  7.75047091e+00,
        1.60656699e-01, -2.08661353e+00,  9.03086149e-01, -6.11273688e-01,
        3.74316794e+00,  2.65605178e-02, -3.07762040e+00,  6.86747689e-01,
       -8.10994416e-01,  2.40672971e+00, -1.06587872e-01, -5.45134011e+00])

In [103]:
np.square(sampleArray)

array([   1,   36,  121,  256,  441,  676,  961, 1296, 1681, 2116, 2601,
       3136, 3721, 4356, 5041, 5776, 6561, 7396, 8281, 9216], dtype=int32)

In [104]:
np.square(10)

100

In [106]:
sampleFloats = np.random.randn(10)
sampleFloats

array([-1.4920051 ,  0.95762739,  0.61954575, -0.90741762,  0.94874731,
       -1.17095649,  1.16480871, -0.15242663,  0.54847727, -0.46144746])

In [107]:
np.round(sampleFloats)

array([-1.,  1.,  1., -1.,  1., -1.,  1., -0.,  1., -0.])

In [110]:
np.round(sampleFloats, decimals=2)

array([-1.49,  0.96,  0.62, -0.91,  0.95, -1.17,  1.16, -0.15,  0.55,
       -0.46])

In [112]:
np.ceil(sampleFloats)

array([-1.,  1.,  1., -0.,  1., -1.,  2., -0.,  1., -0.])

In [113]:
np.floor(sampleFloats)

array([-2.,  0.,  0., -1.,  0., -2.,  1., -1.,  0., -1.])

In [114]:
np.mean(sampleFloats)

0.005495312780114054

In [115]:
np.median(sampleFloats)

0.1980253173155456

In [118]:
np.var(sampleFloats)

0.851510597372191

In [119]:
np.std(sampleFloats)

0.9227733185198795

In [121]:
sampleMatrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
sampleMatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
np.std(sampleMatrix)

2.581988897471611

In [123]:
np.mean(sampleMatrix)

5.0

In [124]:
sports = np.array(['golf', 'cricket', 'golf', 'football', 'baseball', 'foosball', 'rubgy'])
sports

array(['golf', 'cricket', 'golf', 'football', 'baseball', 'foosball',
       'rubgy'], dtype='<U8')

In [127]:
np.unique(sports).size

6

In [128]:
np.unique(sports)

array(['baseball', 'cricket', 'foosball', 'football', 'golf', 'rubgy'],
      dtype='<U8')

### Saving to files

##### Documentation: https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html

In [133]:
np.save('Sports', sports)

In [134]:
np.savez('MultipleArraysArchive.npz', a=sampleMatrix, b=sports)

In [136]:
loadedSports = np.load('Sports.npy')
loadedSports

array(['golf', 'cricket', 'golf', 'football', 'baseball', 'foosball',
       'rubgy'], dtype='<U8')

In [138]:
loadedMultiple = np.load('MultipleArraysArchive.npz')
loadedMultiple

In [140]:
loadedMultiple.files

['a', 'b']

In [141]:
sorted(loadedMultiple.files)

['a', 'b']

In [142]:
loadedMultiple['a']

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [143]:
loadedMultiple['b']

array(['golf', 'cricket', 'golf', 'football', 'baseball', 'foosball',
       'rubgy'], dtype='<U8')

In [146]:
# Saving as text files
np.savetxt('SampleFloats.txt', sampleFloats, delimiter=',')

In [148]:
loadSampleFloats = np.loadtxt('SampleFloats.txt', delimiter=',')
loadSampleFloats

array([-1.4920051 ,  0.95762739,  0.61954575, -0.90741762,  0.94874731,
       -1.17095649,  1.16480871, -0.15242663,  0.54847727, -0.46144746])